# FRC Project Management System - Enhanced with FRC API Integration
# Version 2.0.0 - Phase 3A: FRC API Integration
#
# This configuration adds FIRST Robotics Competition API integration
# for real-time event data, team information, and competition schedules.

spring:
  application:
    name: frc-project-management
  
  # Profile Configuration
  profiles:
    active: development
    
  # JPA Configuration (enhanced for audit logging)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
        cache:
          use_second_level_cache: false
          use_query_cache: false
    defer-datasource-initialization: true
    
  # SQL Initialization
  sql:
    init:
      mode: embedded
      continue-on-error: false
      
  # H2 Console (development only)
  h2:
    console:
      enabled: false  # Enabled in development profile
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
      
  # Thymeleaf Template Engine
  thymeleaf:
    cache: true       # Disabled in development profile
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    
  # Web Resources
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 86400   # 24 hours cache
        cachecontrol:
          max-age: 86400
        
  # Enhanced Security Configuration
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}   # Changed in production
      roles: ADMIN
    
  # Session Management (enhanced for role-based timeouts)
  session:
    store-type: jdbc
    timeout: 30m      # Default timeout
    cookie:
      name: FRCPM_SESSION
      http-only: true
      secure: ${COOKIE_SECURE:false}
      same-site: strict
      
  # Mail Configuration for COPPA notifications
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Server Configuration (enhanced security headers)
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m
      cookie:
        name: FRCPM_SESSION
        http-only: true
        secure: ${COOKIE_SECURE:false}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  
  # Security headers
  forward-headers-strategy: framework

# Enhanced Logging Configuration
logging:
  level:
    org.frcpm: INFO
    org.frcpm.security: DEBUG
    org.frcpm.integration.frc: DEBUG  # FRC API integration logging
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/frc-project-management.log
    max-size: 10MB
    max-history: 30

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,auditevents
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    auditevents:
      enabled: true
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: FRC Project Management System
    version: 2.0.0
    description: Web-based project management system for FIRST Robotics Competition teams
    team: FRC Project Management Team
  migration:
    from: JavaFX MVVM Application
    to: Spring Boot Web Application
    phase: "Phase 3A - FRC API Integration"
  frc:
    api:
      version: "3.0"
      integration: "Real-time event data and team synchronization"
    features:
      - "Live competition schedules"
      - "Team rankings and match results"
      - "Event timeline integration"
      - "Automated deadline management"
    
# FRC-Specific Application Properties (Enhanced for API Integration)
app:
  name: FRC Project Management System
  version: 2.0.0
  description: Project management system for FIRST Robotics Competition teams
  
  # Team Configuration
  team:
    default-name: ${TEAM_NAME:FRC Team}
    default-number: ${TEAM_NUMBER:0}
    contact-email: ${TEAM_EMAIL:team@example.com}
    
  # Security Configuration
  security:
    # Password requirements
    password:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: false
      max-age-days: 90
    
    # Session configuration
    session:
      student-timeout: 900     # 15 minutes for students
      mentor-timeout: 1800     # 30 minutes for mentors
      admin-timeout: 1800      # 30 minutes for admins
      parent-timeout: 1800     # 30 minutes for parents
      remember-me-validity: 86400  # 24 hours
    
    # MFA Configuration
    mfa:
      issuer: "FRC Project Management"
      token-length: 6
      window-size: 1
      secret-length: 20
      qr-code-size: 200
      
    # Account lockout settings
    lockout:
      max-attempts: 5
      lockout-duration: 300    # 5 minutes
      
  # COPPA Compliance Configuration
  coppa:
    enabled: true
    age-threshold: 13
    consent-email-template: classpath:templates/email/parental-consent.html
    consent-url-base: ${BASE_URL:http://localhost:8080}/coppa/consent
    consent-expiry-days: 30
    data-retention-days: 2555  # 7 years as per COPPA
    reminder-interval-days: 7
    
  # Audit Configuration
  audit:
    enabled: true
    retention-days: 2555       # 7 years for compliance
    coppa-log-all: true        # Log all access to COPPA-protected data
    security-events: true
    cleanup-interval-hours: 24
    
  # Email Configuration
  email:
    from-address: ${FROM_EMAIL:noreply@frcteam.org}
    from-name: ${FROM_NAME:FRC Project Management System}
    support-email: ${SUPPORT_EMAIL:support@frcteam.org}
    
  # Build Season Configuration
  build-season:
    default-length-weeks: 6
    default-competition-buffer-days: 7
    
  # Project Configuration
  project:
    max-active-projects: 5
    default-milestone-count: 4
    
  # Task Configuration  
  task:
    max-dependencies: 10
    default-progress-increment: 5
    
  # Meeting Configuration
  meeting:
    default-duration-minutes: 120
    max-attendees: 50
    
  # File Upload Configuration
  upload:
    max-file-size: 10MB
    allowed-extensions: pdf,doc,docx,xls,xlsx,png,jpg,jpeg,gif
    
  # Export Configuration
  export:
    pdf-enabled: true
    excel-enabled: true
    json-enabled: true
    
  # Chart Configuration
  charts:
    gantt-enabled: true
    metrics-enabled: true
    default-chart-height: 400

  # 🚀 NEW: FRC API Integration Configuration
  frc:
    api:
      # FIRST API Configuration
      enabled: false  # Temporarily disable FRC API service
      base-url: ${FRC_API_BASE_URL:https://frc-api.firstinspires.org/v3.0}
      username: dhiebert7251
      key: 4a986fab-899a-440b-8431-502c399eaea5
      team:
        number: 2408
      #username: ${FRC_API_USERNAME:}
      #auth-key: ${FRC_API_AUTH_KEY:}
      rateLimitPerMinute: 120  # Add missing rate limit config for future use
      
      # API Rate Limiting
      rate-limit:
        requests-per-minute: 20
        burst-requests: 5
        retry-delay-seconds: 30
        max-retries: 3
      
      # Data Sync Configuration
      sync:
        enabled: ${FRC_SYNC_ENABLED:true}
        auto-sync-interval: 3600  # 1 hour in seconds
        team-data-sync: true
        event-data-sync: true
        ranking-data-sync: true
        match-result-sync: true
      
      # Cache Configuration
      cache:
        enabled: true
        ttl-seconds: 1800        # 30 minutes cache
        max-entries: 1000
        
      # Competition Season Configuration
      season:
        current-year: ${FRC_SEASON_YEAR:2025}
        kickoff-auto-detection: true
        competition-buffer-days: 7
        
      # Event Types to Sync
      event-types:
        - "Regional"
        - "District"
        - "Championship"
        - "Offseason"
        
      # Data Mapping Configuration
      mapping:
        # Map FRC events to project deadlines
        events-to-projects: true
        # Map match schedules to tasks
        matches-to-tasks: true
        # Map team roster to team members
        roster-to-members: false  # Manual only due to COPPA
        
      # Notification Configuration
      notifications:
        ranking-changes: true
        match-schedule-updates: true
        event-announcements: true
        deadline-alerts: true
        
      # Error Handling
      error-handling:
        continue-on-api-error: true
        fallback-to-cache: true
        log-api-errors: true
        notify-admins-on-failure: true



# Health Checks (Enhanced with FRC API)
health:
  database:
    enabled: true
  diskspace:
    enabled: true
    threshold: 100MB
  mail:
    enabled: true
  frc-api:
    enabled: true
    timeout: 10s

# 🎯 Environment Variables for FRC API Integration
# Add these environment variables for production:
#
# Required FRC API:
#   FRC_API_USERNAME - Your FRC API username
#   FRC_API_AUTH_KEY - Your FRC API authorization key
#   
# Optional FRC Configuration:
#   FRC_API_BASE_URL - Custom API base URL (default: official FIRST API)
#   FRC_SYNC_ENABLED - Enable/disable automatic sync (default: true)
#   FRC_SEASON_YEAR - Current competition season year (default: 2025)
#   
# Team Configuration:
#   TEAM_NAME - FRC team name
#   TEAM_NUMBER - FRC team number (required for API calls)
#   TEAM_EMAIL - Team contact email
#   
# Example Production Setup:
#   export FRC_API_USERNAME=your-frc-username
#   export FRC_API_AUTH_KEY=your-frc-auth-key
#   export TEAM_NUMBER=1234
#   export TEAM_NAME="Robotics Warriors"
#   export FRC_SEASON_YEAR=2025
#   export FRC_SYNC_ENABLED=true
#
# Getting FRC API Credentials:
# 1. Register at https://frc-events.firstinspires.org/services/API
# 2. Request API access for your team
# 3. Obtain username and authorization key
# 4. Set environment variables before starting application